---
repo_url: https://github.com/jasonpatrickellykrause/crossfit-help/blob/main/docs/
site_description: Open sourcing CrossFit documentation
site_name: CrossFit Help
site_url: https://crossfit.help
theme:
  logo: /assets/logo.png
  name: readthedocs