---
markdown_extensions:
  - callouts
plugins:
  - autolinks
  - callouts
  - mkdocs-video
  - search
site_description: Open sourcing CrossFit documentation
site_name: CrossFit Help
site_url: https://crossfit.help
theme:
  logo: /assets/logo.png
  name: readthedocs
